[package]
name = "humanode-distribution-resolver"
version = "0.1.0"
edition = "2021"

[dependencies]
humanode-distribution-schema = { path = "../schema" }

futures = "0.3"
reqwest = "0.11"
serde = "1.0"
serde_yaml = "0.9"
thiserror = "1"
