[package]
name = "humanode-distribution-resolver"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
humanode-distribution-schema = { path = "../schema" }

futures = "0.3"
reqwest = { version = "0.12", default-features = false }
serde = "1.0"
serde_yaml = "0.9"
thiserror = "2"
