cargo-features = ["profile-rustflags"]

[workspace]
resolver = "2"
members = ["crates/*"]

[profile.dev.package.humanode-distribution]
rustflags = ["-C", "target-feature=+crt-static"]

[profile.release.package.humanode-distribution]
rustflags = ["-C", "target-feature=+crt-static"]
