[package]
name = "humanode-distribution-schema"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_json = "1"
serde_yaml = "0.9"
