[package]
name = "humanode-distribution-config"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
dirs = "4"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "1"
tokio = { version = "1", features = ["fs"] }
